### ISSUE TITLE
Heading widget/gauge OSD element ticker bar counts over 360 degrees

### ISSUE THREAD

**Issue by joosttromp** [PetruSoroaga/RubyFPV#10]
**Steps to reproduce:**
Enable Telemetry from FC
Enable "Show Heading" in Vehicle settings -> OSD / Instruments -> Layout OSD Widgets & Gauges -> OSD Widgets.
Move Current heading to =< 359 and > 330 to keep every heading over North in view.

**Current behaviour:**
The headings past North read 370, 380, 390, 400, etc.
Go past a current heading of => 000 (N) and It'll read 10, 20, 30, etc.

**Expected behaviour:**
That also when the heading is =< 359, that the headings in the ticker bar show 10, 20, 30, etc.

**Example:**
The issue can be observed in this video
https://youtu.be/H92Wab901v4?si=36E9Pp9BzHqZ8B_X&t=30
watch as at 0:35 the heading goes through north. and the digits on the right side of North well have 360 degrees added to them.

This issue is present on Ruby 9.4 at the time of writing.

**Comment by PetruSoroaga** [comment]
Fixed. Will be in next update.

**Comment by PetruSoroaga** [comment]
Done
