### ISSUE TITLE
MSP OSD Updates Freeze on INAV

### ISSUE THREAD

**Issue by RomanLut** [PetruSoroaga/RubyFPV#17]
Issue:
When using INAV 7.0.1 with the flight controller connected to RPI02W GS, the MSP OSD updates for 1 second, then freezes for 1 second, and continues in this pattern.

Cause:
INAV expects the VTX to send an MSP command at least once every second:(https://github.com/iNavFlight/inav/blob/f3da48726429abf7e26d8ab104d7ce2d46d9bccc/src/main/io/displayport_msp_osd.c#L518)

However, currently, RubyFPV sends the ```MSP_CMD_BATTERY_STATE``` command every 2000ms:(https://github.com/PetruSoroaga/RubyFPV/blob/948b08a07703f3716850a93aa3b39e19ba08aec3/code/r_vehicle/telemetry_msp.cpp#L125)

Possible Solution:
Change the command interval from 2000ms to 500ms to meet the expected frequency for INAV.

**Comment by PetruSoroaga** [comment]
Resolved in 4.8

**Comment by RomanLut** [comment]
Confirmed fixed in 9.8
